name: Deploy to GitHub Pages # name 工作流名

on: # 触发工作流的 github 事件, 例如 push, pull_request 等
  push: # push 操作时触发
    tags: # 在指定 tag 上的操作, 才会触发工作流
      - 'v*.*.*' # 指定 tag
# 例如在 tag v0.0.1 上的 push 操作, 才会触发工作流

jobs: # job 工作流中的作业
  build-and-deploy: # 作业名 build-and-deploy
    runs-on: ubuntu-latest # 指定操作系统

    steps: # step 作业中的步骤
      - name: Checkout Repository # name 步骤名
        uses: actions/checkout@v3 # 使用预定义的 actions/checkout 检出代码

      - name: Setup Node.js
        uses: actions/setup-node@v3 # 使用预定义的 actions/setup-node 设置 Node.js 环境
        with: # 动作的参数
          node-version: 22 # 指定 Node.js 版本

      - name: Clear Cache
        run: | # 运行命令或脚本, | 表示多行命令
          rm -rf node_modules # 删除 node_modules 目录。

      - name: Install Dependencies
        run: npm install # 安装依赖

      - name: Build Project
        run: npm run build # 构建项目

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # 使用预定义的 peaceiris/actions-gh-pages 部署项目到 GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: '161043261'
          user_email: '161043261@qq.com'
